### ISSUE TITLE
Does not support redirecting to from page

### ISSUE THREAD

**Issue by peteruithoven** [devbytecom/react-protected-route#1]
Thanks for making this publicly available! 

I'd love to be able to easily create a `/login` route that, when the user is authenticated, he/she is automatically redirected to the specific protected route he started on. 
I think this can be done by:
1. Including "from" location so enable dynamic redirects back to the protected page the user started on
2. Using this "from" information as redirect option, making this available with a optional property like `useFrom`.

I've created an example where I used your ProtectedRoute as a base:
https://github.com/peteruithoven/protected-route-example

The alternative version: https://github.com/peteruithoven/protected-route-example/blob/master/src/ProtectedRoute.js

My approach is inspired by: https://reacttraining.com/react-router/web/example/auth-workflow

Are you open for pull requests?

**Comment by devbytecom** [comment]
Great idea!, yeah open to pull requests
